# packcheck-0.7.1
# You can use any of the options supported by packcheck as environment
# variables here.  See https://github.com/composewell/packcheck for all
# options and their explanation.
#
branches:
  only:
    - master

environment:
    # ------------------------------------------------------------------------
    # Global options, you can use these per build as well
    # ------------------------------------------------------------------------
  global:
    # ------------------------------------------------------------------------
    # Common options
    # ------------------------------------------------------------------------
    CABAL_REINIT_CONFIG: "y"
    LC_ALL: "C.UTF-8"

    # ------------------------------------------------------------------------
    # How to build
    # ------------------------------------------------------------------------
    #
    GHCUP_VERSION: "0.1.50.2"
    GHCVER: "9.10.3"
    #CABALVER: "3.10.3.0"

    # ------------------------------------------------------------------------
    # What to build
    # ------------------------------------------------------------------------
    # DISABLE_TEST: "y"
    # DISABLE_BENCH: "y"
    # DISABLE_DOCS: "y"
    DISABLE_DIST_CHECKS: "y"
    DISABLE_SDIST_BUILD: "y"
    # Note: these require the "diff" utility.
    # DISABLE_SDIST_GIT_CHECK: "y"
    # DISABLE_SDIST_PROJECT_CHECK: "y"

    # ------------------------------------------------------------------------
    # cabal options
    # ------------------------------------------------------------------------
    CABAL_CHECK_RELAX: "y"
    CABAL_PROJECT: "cabal.project"

    # ------------------------------------------------------------------------
    # Location of packcheck.sh (the shell script invoked to perform CI tests ).
    # ------------------------------------------------------------------------
    # You can either commit the packcheck.sh script at this path in your repo or
    # you can use it by specifying the PACKCHECK_REPO_URL option below in which
    # case it will be automatically copied from the packcheck repo to this path
    # during CI tests. In any case it is finally invoked from this path.
    PACKCHECK_LOCAL_PATH: "./packcheck.sh"
    # If you have not committed packcheck.sh in your repo at PACKCHECK_LOCAL_PATH
    # then it is automatically pulled from this URL.
    PACKCHECK_GITHUB_URL: "https://raw.githubusercontent.com/composewell/packcheck"
    PACKCHECK_GITHUB_COMMIT: "fac7ab9aad48d5b80a1d65efb34ff353a848e927"

    # Override the temp directory to avoid sed escaping issues
    # See https://github.com/haskell/cabal/issues/5386
    TMP: "c:\\tmp"

# Bump the -> version to clear the cache
# packcheck uses "%APPDATA%\\local" to install tools like hlint etc.
# cabal may use "%APPDATA%\\cabal" or "c:\\cabal"
# ghcup may use "%APPDATA%\\ghcup" or "c:\\ghcup"
cache:
  - "%APPDATA%\\local\\bin -> v1"
  - "%APPDATA%\\cabal"
  - "C:\\ghcup"
  - "C:\\cabal"

# Folder where the repository is cloned.
clone_folder: "c:\\pkg"
build: off

before_test:
- if not exist %PACKCHECK_LOCAL_PATH% curl --fail -sSL -o%PACKCHECK_LOCAL_PATH% %PACKCHECK_GITHUB_URL%/%PACKCHECK_GITHUB_COMMIT%/packcheck.sh

test_script:
- for /f "usebackq tokens=*" %%i in (`where 7z.exe`) do set PATH7Z=%%i\..
- for /f "usebackq tokens=*" %%i in (`where git.exe`) do set PATHGIT=%%i\..
- for /f "usebackq tokens=*" %%i in (`where curl.exe`) do set PATHCURL=%%i\..
- chcp 65001
- bash %PACKCHECK_LOCAL_PATH% cabal PATH="/usr/bin:%PATH7Z%:%PATHGIT%:%PATHCURL%"
