resolver: nightly-2026-03-10
packages:
- '.'
- './benchmark'
- './test'
- './core'
- './bench-test-lib'

# network 3.2.8 is broken
extra-deps:
  - network-3.2.7.0

#allow-newer: true
rebuild-ghc-options: true

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
