resolver: lts-18.27
packages:
- '.'
- './benchmark_core'
- './benchmark'
- './test'
- './core'

extra-deps:
  - unicode-data-0.2.0
  - tasty-bench-0.3.1

#allow-newer: true
rebuild-ghc-options: true

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
