resolver: lts-11.0
packages:
- '.'
extra-deps:
    - simple-conduit-0.6.0
    - SDL-0.6.5.1
flags: {}
extra-package-dbs: []
rebuild-ghc-options: true
# For mac ports installed SDL library on Mac OS X
#extra-include-dirs:
#- /opt/local/include
