resolver: lts-13.13
packages:
- '.'
extra-deps:
    - SDL-0.6.6.0
    - Chart-1.9.1
    - Chart-diagrams-1.9.2
    - bench-show-0.2.2

    - diagrams-postscript-1.4.1@sha256:a39c44f8a93929de88e5c363290d5bb8bc93ba15cd36af5c9ca5b620d51cdf68
    - network-3.1.0.0@sha256:85b36fea1dfe92af91b38224d6ea84eb0b17c03d9aed0260413be226722b0cd2

#allow-newer: true
flags: {}
extra-package-dbs: []
rebuild-ghc-options: true
# For mac ports installed SDL library on Mac OS X
extra-include-dirs:
- /opt/local/include
