resolver: lts-24.8
packages:
- '.'
- './benchmark'
- './test'
- './core'
- './bench-test-lib'

extra-deps:
  #- tasty-bench-0.3.1
  - lockfree-queue-0.2.4
  - unicode-data-0.6.0

#allow-newer: true
rebuild-ghc-options: true

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
