name: Packdiff

on: pull_request

jobs:
  packdiff:

    runs-on: ubuntu-latest

    steps:

    - name: Download ghc
      run: |
        GHCUP_VER=0.1.20.0
        curl -sL -o ./ghcup https://downloads.haskell.org/~ghcup/$GHCUP_VER/x86_64-linux-ghcup-$GHCUP_VER
        chmod +x ./ghcup
        GHCVER=9.8.1
        ./ghcup install ghc $GHCVER
        ./ghcup set ghc $GHCVER
        cabal update

    - uses: actions/cache@v2
      name: Cache ~/.cabal
      with:
        path: |
            ~/.cabal
        # Bump the key version to clear the cache
        key: cache-v2

    - name: Checkout the current branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run packdiff on streamly-core
      run: cabal run packdiff --project-file=cabal.project.packdiff -- streamly-core $(git rev-parse origin/master) $(git rev-parse HEAD)

    - name: Run packdiff on streamly
      run: cabal run packdiff --project-file=cabal.project.packdiff -- streamly $(git rev-parse origin/master) $(git rev-parse HEAD)
